### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by DBTDerpbox** [LOOHP/Limbo#10]
Velocity is a server proxy, similar to BungeeCord, if it wouldn't be too much of a hassle adding [VelocityPowered](https://velocitypowered.com/) would be preferred. Thank you.

**Comment by LOOHP** [comment]
I'll take a look at that when I have time :)

**Comment by Romvnly-Gaming** [comment]
Just a update - this would work but I'm trying to use modern forwarding and such! I can't wait for this project to support Velocity!
