### ISSUE TITLE
Error when pinging

### ISSUE THREAD

**Issue by wisingman** [LOOHP/Limbo#16]
When pinging the server via socket connection check in proxy it runs this error in the Limbo console

```
[12:19:13 Error]java.io.EOFException
[12:19:13 Error]        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
[12:19:13 Error]        at com.loohp.limbo.utils.DataTypeIO.readVarInt(DataTypeIO.java:65)
[12:19:13 Error]        at com.loohp.limbo.server.ClientConnection.run(ClientConnection.java:179)
```

The ping still works, but that error is now sent every 5 seconds
Thanks

**Comment by LOOHP** [comment]
Is it a modern server list ping or a legacy ping?

**Comment by wisingman** [comment]
This is a socket ping from a bungee plugin running the latest version of waterfall

**Comment by wisingman** [comment]
Also to add to this I'm having a problem with the API for a seperate plugin on the Limbo where it recieves packets from the rest of the network to execute tasks like staff chat & punishments but it's doing this:

`java.lang.ClassCastException: class <CORE_CLASS> cannot be cast to class com.loohp.limbo.plugins.LimboPlugin (<CORE_CLASS> is in unnamed module of loader java.net.URLClassLoader @21be3395; com.loohp.limbo.plugins.LimboPlugin is in unnamed module of loader 'app')`

That's using the following dependancy
`<dependency>
            <groupId>com.loohp</groupId>
            <artifactId>Limbo</artifactId>
            <version>0.4.0-ALPHA</version>
        </dependency>`

Any ideas?
All the best

**Comment by LOOHP** [comment]
Does your main class extends LimboPlugin?
Also try 0.4.4-ALPHA instead.

**Comment by wisingman** [comment]
It does extend it indeed, I'll try that out now thanks.

**Comment by wisingman** [comment]
It can't find that in https://repo.loohpjames.com/repository

**Comment by LOOHP** [comment]
I made a mistake, 0.4.4-ALPHA should be available now
