### ISSUE TITLE
Feature Request: Use many protocols, queue, and ability to use no schematic

### ISSUE THREAD

**Issue by TheMonBonGH** [LOOHP/Limbo#20]
I want this program to use many protocols without installing ViaVersion on the Bungee. I also want this to have a queue system when the lobby is full (and has auto server switching when lobby server is down), and want to use no schematic in the end dimension, to act like a queue in 2B2T.

**Comment by LOOHP** [comment]
Schematic defines the size of your world, you can just provide an empty schematic, Player queue will probably need to be controlled by the proxy.
As for multiple version, I would love to be able to do that. However, it would be quite time consuming to implement, tho it might happen in the future.
