### ISSUE TITLE
Plugin Development?

### ISSUE THREAD

**Issue by TheChemicalWorkshop** [LOOHP/Limbo#26]
I'm in love with this project...

Can we get some tutorial/Ressource/anything for writing a plugin for this?
I would like very basic functionality like, sending people over bungee back.

Tho no idea where to start/what compiler settings to choose

Thanks

**Comment by TheChemicalWorkshop** [comment]
i got plugins to work
a documentation would be nice...

I'll release files to make your own plugins soon

**Comment by LOOHP** [comment]
I wanted to add documentations to Limbo for a long time :/ Unfortunately I got busy with irl stuff and wasn't able to do that yet. There is no timeline on this but it's definitely on to-do.

**Comment by TheChemicalWorkshop** [comment]
> 

might actually do this as a video and or github repo...

**Comment by TheChemicalWorkshop** [comment]
https://github.com/TheChemicalWorkshop/LimboMC-Plugin-Example
github repo for the files...

https://youtu.be/LsiBf3RmOv0
TERRIBLE youtube tutorial

you can use the code/files freely and video with atribution

**Comment by LOOHP** [comment]
Thank you! Maybe other users will find these useful!
