### ISSUE TITLE
Error when using /kick

### ISSUE THREAD

**Issue by sqcred** [LOOHP/Limbo#31]
I found out that when i use /kick and I kick myself i got this error.
Hope this helps
![error](https://user-images.githubusercontent.com/67073397/138570648-26163992-8b17-48d0-bb4a-bc8ae39ac384.PNG)

**Comment by GamerDuck123** [comment]
This is just an error when you kick yourself because you're trying to dispatch a command at the same time as disconnecting.

**Comment by LOOHP** [comment]
Resolved in 0.6.4
