### ISSUE TITLE
Half of limbo world invisible?

### ISSUE THREAD

**Issue by GamerDuck123** [LOOHP/Limbo#33]
So we are currently using a fork of limbo (that only adds resourcepack packets into it I haven't touched the world, I'm also planning on making a commit with the resourcepack code soon also all of this was happening before we forked the jar) but we seem to be having a problem where half of the schematic is invisible, as in the blocks are still there, and still have their data (if I middle-click it gives me the right block) but you can't see them, they kind of act like barrier blocks. I played around in the jar trying to edit the world generation to see if I can fix it, but I haven't found a fix yet! Please let me know if anyone else has a fix for this!
Thank you all!

![image](https://user-images.githubusercontent.com/30637585/140622517-64e20e05-75dc-4ab4-a8e7-e5e66fac1411.png)

**Comment by GamerDuck123** [comment]
So it turns out the problem comes with fabric we think the sodium mod (both the owner and I use it so we didn't know regular players saw it normally)

**Comment by TheChemicalWorkshop** [comment]
hey @GamerDuck123 add me on discord, this hole is very deep ! Matti (The Chemical Workshop)#5451
i already reached out to MANY people and did some research... add me i'll point you further
