### ISSUE TITLE
Previous version support

### ISSUE THREAD

**Issue by zReport02** [LOOHP/Limbo#38]
Hi, I would like to ask if it was possible to put the ability to enter from previous versions?
I have server 1.18 and I wish players could join 1.8!

I have seen that there is a possibility to do this with ViaVersion and ViaBackWards etc. in the proxy, but use these plugins in the proxy it is quite heavy and not recommended and I would like to avoid!

Is it possible to have it?

**Comment by LOOHP** [comment]
This is a heavily requested feature and it might come in the future. There is not ETA atm tho.
