### ISSUE TITLE
Cannot join Limbo

### ISSUE THREAD

**Issue by drunderscore** [LOOHP/Limbo#44]
The stacktrace is not present in the `latest.log`, and it is absolutely impossible to fit on the screen -- I resized the window well over 3 monitors horizontally and vertically an incredible amount to get to the start of the exception.

Running `0.6.12-ALPHA-1.18.2`

![Screenshot from 2022-03-17 12-35-32](https://user-images.githubusercontent.com/15949431/158849526-0373dcaa-e883-4b62-9044-359718a1bef0.png)

Using Waterfall 1.18.2 `e767b40`

All the Limbo log shows is:
```
[12:36:29 Info] [address here|DrUnderscore(45cfb71f-e464-44b5-a97f-39f0566f8025)] <-> Player had
connected to the Limbo server!
```

Waterfall shows:
```
[16:40:41 INFO]: [address here] <-> InitialHandler has connected
[16:40:41 INFO]: [DrUnderscore|address here] <-> ServerConnector [limbo] has connected
[16:40:42 INFO]: [address here|DrUnderscore] -> UpstreamBridge has disconnected
[16:40:42 INFO]: [address here|DrUnderscore] <-> DownstreamBridge <-> [limbo] has disconnected
```

Custom `spawn.schem` is in use, but even replaced with the default it does not work.

`server.properties`
```
#For explaination of what each of the options does, please visit:
#https://github.com/LOOHP/Limbo/blob/master/src/main/resources/server.properties
#Thu Mar 17 12:42:22 EDT 2022
reduced-debug-info=false
default-gamemode=adventure
required-resource-pack=false
view-distance=6
server-ip=0.0.0.0
resource-pack-prompt={"text"\:"","extra"\:[{"text"\:"Install server resource pack\!","color"\:"yellow"}]}
server-port=25567
tab-header=
bungeecord=true
resource-pack=
forwarding-secrets=secret here
level-name=world;spawn.schem
ticks-per-second=5
world-spawn=world;22.5;5;17;0;0
motd={"text"\:"","extra"\:[{"text"\:"Limbo Server\!","color"\:"yellow"}]}
allow-chat=false
tab-footer=
version=Limbo\!
level-dimension=minecraft\:the_end
bungee-guard=false
max-players=-1
handshake-verbose=true
resource-pack-sha1=
velocity-modern=false
allow-flight=false
```

**Comment by drunderscore** [comment]
A local test on my personal machine showed no issues, issues seems to be not with Limbo, but still no clue what would cause this, nor why it would.

**Comment by drunderscore** [comment]
`internal_data` directory had to be deleted manually, and it worked. Is this expected?

**Comment by LOOHP** [comment]
Yes, for now whenever you update the limbo jar, you should reset the `internal_data` directory.

**Comment by drunderscore** [comment]
Alright, thanks for the info!
