### ISSUE TITLE
shem and API questions

### ISSUE THREAD

**Issue by fulcanelly** [LOOHP/Limbo#8]
How to edit .shem file ? 

Any editors don't seems to support this format, and any googled extraneous .shem file dont seems supportws by server as weel (throws NPE or OutOfBoundaries).

And what API does it uses, is there any documnatation ?

**Comment by LOOHP** [comment]
Do you mean the .schem file?
It is the format used by plugins such as worldedit. You can get a .schem file by saving a schematic in worldedit and grabbing the file from its plugin folder.

**Comment by jehendeoff** [comment]
To answer the documentation question, I didn't find any.
But it seems to be easy to use with eclipse (I'm trying it out rn)

If I get any result, whatsoever, I'll send a reply with a repo of what I could find.

**Comment by jehendeoff** [comment]
After digging a bit, I discovered that what I thought was an api was really limited, which I can understand was that it wasn't meant to have plugins in the first place.

There are only two things that were really implemented if you want to make a plugin: a tab executor and a command listener (I think ?)

**Comment by LOOHP** [comment]
Events are a thing as well, Entities are being slowly implemented as well. Armorstands is the only one implemented atm.
