### ISSUE TITLE
Basic suggestion

### ISSUE THREAD

**Issue by jehendeoff** [LOOHP/Limbo#9]
Actually, I find this limbo to be one that works like intented 100% percent of the time, but what i think it lacks is : 
   - join messages
   - bossbar
   - tab header/footer

if you implemented / make a plugins for those things, I think it would be the best limbo server out there

**Comment by jehendeoff** [comment]
Or (for me), it would be as great as having the "LimboDefaultCmd.jar" plugin open-sourced, since I could create another plugin wich would do what I need

**Comment by LOOHP** [comment]
> having the "LimboDefaultCmd.jar" plugin open-sourced

I will probably do that in the near future.
